all:
	# generate documentation 2 times because this is how table of contents generation works
	pdflatex usage.tex
	pdflatex usage.tex
	pdflatex modules.tex
	pdflatex modules.tex
	pdflatex protocol.tex
	pdflatex protocol.tex
